version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 25432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    # network_mode: host
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blogs_posts